version: '3.9'

services:
  django-app:
    container_name: django-app
    env_file:
      - ./.env    
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${POSTGRESDB_NAME}
      DB_USER: ${POSTGRESDB_USER}
      DB_PASSWORD: ${POSTGRESDB_PASSWD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db_0001
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRESDB_NAME}
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESDB_USER}"]
      interval: 10s  
      retries: 5    

    volumes:
      - postgres_test_db_data:/var/lib/postgresql/data/

volumes:
  postgres_test_db_data:
